[default]

runs_on = ["linux", "windows", "macos"]
windows_shell = "powershell"
code = 0
timeout = 15

[test.echo]

cmd = "echo hello world"

stdout = """
hello
world
"""

[test.SimplePrint]

code = 0
timeout = 5

cmd = "python3 printer_stdin.py"
stdin = "hey"
stdout = """
hey
"""
stderr = ""

# disable stdout and stderr catch for this test:

[test.ZZZzzz]

timeout = 5

cmd = "sleep 10"
stdout = ""
stderr = ""

[test.crash]

cmd = "./a.out"

stdout = """
test
dz
dzdz
"""
stderr = ""

[test.stdin]

cmd = "python3 printer_stdin.py"

stdin = """
hey
brother
"""
stdout = """
hey

brother

"""
stderr = ""