name: CI

on: [push, pull_request]

defaults:
    run:
        shell: bash

jobs:
    build_and_test:
        strategy:
            fail-fast: false
            matrix:
                os: [windows-latest, ubuntu-latest, macos-latest]

        name: ${{ matrix.os }}
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v2

            - name: Build Project
              run: cargo build

            - name: Install Project
              run: cargo install --path .

            - name: Check Install
              run: io_tester --help