name: Build

on: [push]

defaults:
    run:
        shell: bash

jobs:
    build_ubuntu:
        name: build ubuntu
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: make IO_Tester
              run: make

    build_macos:
        name: build macOS
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2

            - name: make IO_Tester
              run: make